dist: trusty
sudo: required
language: bash
before_install:
- mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin
- cd /tmp
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo add-apt-repository ppa:jonathonf/python-2.7 -y
- sudo apt-get update -y
- sudo apt-get install python2.7 -y
- sudo -H pip install ansible-lint ; ansible --version
- curl --silent --output packer.zip https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip ; unzip packer.zip ; rm -f packer.zip ; chmod +x packer ; mv packer ${HOME}/bin/ ; packer -v
- curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/0.12.12/terraform_0.12.12_linux_amd64.zip ; unzip terraform.zip ; rm -f terraform.zip ; chmod +x terraform ; mv terraform ${HOME}/bin/ ; terraform -v
- curl -L "$(curl -s https://api.github.com/repos/wata727/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip ; unzip tflint.zip ; rm tflint.zip ; chmod +x tflint ; mv tflint ${HOME}/bin/ ; tflint -v
- cd ${TRAVIS_BUILD_DIR}
- curl https://gist.githubusercontent.com/kovtalex/6bca8d3ea9368c0dbe8deb50b6f16e38/raw/3c1590f2a824208aae1af4846d9901073f31811f/travis.sh |
  bash
- cd ${TRAVIS_BUILD_DIR}
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: jpXXVcYXh85mUhdgA8QdN3fX3WzkCsDnp6ZyUEH6oO/F4MOTyrCgrIHA0DmYqrk5Q9xf6M/qSTpaCUUFsEbI66dYZNWFtiv6e20JvK4czj/cMgYrxfxzwORDDHI0XN64n3e21pnRGJtCrx0kG5twwRENUmIIuUvDiF/DB45V1AtkZ+31fifk6L3GSM2nrk1pUT5WL/2BUKX6qVdpCnD4OJplVg4e1vlU7bvK5tP/kNK6KSBgtnjhvqY8S3vOrYKEeU2wUJChzxlT25Eul3ryCjQKRwm/xPc/b/xsYQ3i4U59vyZdVTQt86uQueJM8lCzf9O5aMkhVZv6wdnmc4zStVzAbPSoL8qHNts/OZQmKGdx0MgrJLltGZey1zNTk6iQ6o1szT3i9x126kRvuDT+476+LB0YTKrsT/twNC4/fJKl614QioDtTpJ/dxj1R4tp6fmizyMZ8Oh8r+LdVet/wGai8LVg6LGVSUYWF5iHZlDGKbslZf3O5pgHvD3wwyKXaPGh8nYVebFlHzyrTDGA++MezXNDxx2lPO5MdB18ZAZD/s6/i4MPs6EnoNGfk+NF1xTPRkLOhFxX9IlhTBntNUfQWSBeabTpaMaLqfJjm3p3qlYb4qD+jFsiJ5g4ZdkNmheQXRbqudnv3llgwF5vr4XiksY3LD06fCExMSo9kSM=
