---
plugin: gcp_compute  
projects:
  - infra-253207                
regions:                                
  - europe-west1
hostnames:
  - name
groups:
  app: "'-app' in name"
  db:  "'-db' in name"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  internal_ip:  networkInterfaces[0].networkIP
filters: []
auth_kind: serviceaccount     
service_account_file: ~/key.json
